name: Make Distribution

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - if: matrix.os == ubuntu-20.04
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libclang-dev libgtk3-dev libwebkit2gtk-4.0-dev librsvg2-dev
        dist/mkdist-linux ${{ github.ref_name }}
    - uses: actions/upload-artifcat@v3
      with:
        path: dist/*.(dmg|tar.bz2|zip)
