name: Make Distribution

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y libclang-dev libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev
        dist/mkdist-linux ${{ github.ref_name }}
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.bz2
