name: Make Distribution

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libclang-dev libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev
          dist/mkdist-linux ${{ github.ref_name }}
      - if: ${{ matrix.os == 'windows-latest' }}
        run: |
          dist/mkdist-windows.ps1 ${{ github.ref_name }}
      - uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/*.tar.bz2
            dist/*.zip
